MONGODB_DB = 'filebox'
MONGODB_HOST = 'mongodb://localhost'

FILEBOX_PORT = 5050
FILEBOX_SERVER = '0.0.0.0'
FILEBOX_MAX_FILE_SIZE = 10 * 1000 * 1000   # 10 MB

MAX_CONTENT_LENGTH = FILEBOX_MAX_FILE_SIZE
